name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Use a newer Flutter version that includes Dart SDK >=3.4.0
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./flutter_app

      - name: Build Flutter web
        run: flutter build web --release
        working-directory: ./flutter_app

      - name: Deploy to S3
        run: |
          aws s3 sync ./flutter_app/build/web s3://${{ secrets.S3_BUCKET_NAME }} --delete
        
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
