name: Flutter CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        working-directory: ./flutter_app
        run: flutter pub get

      - name: Run tests
        working-directory: ./flutter_app
        run: flutter test
