name: Build and Deploy Flutter Web App

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow write access to the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Or your preferred channel

      - name: Get Flutter dependencies
        working-directory: ./flutter_app
        run: flutter pub get

      - name: Build Flutter web app
        working-directory: ./flutter_app
        run: flutter build web --release --base-href /flutter-cafe-app-ai/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./flutter_app/build/web
          # cname: your-custom-domain.com # Optional: if you have a custom domain
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Flutter Web App to GitHub Pages'
